require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
-- require "user.bufferline"
require("bufferline").setup()
require "user.nvim-tree"
require "user.toggleterm"
vim.cmd "colorscheme aurora"
